const ck100Data = [
  { "oznaka": "CK1",   "datum": "28.04.2026", "lokacija": "Črni mul",                    "slika": "jpg-small/ck001---20260428_183026.jpg" },
  { "oznaka": "CK2",   "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK3",   "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK4",   "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK5",   "datum": "28.04.2026", "lokacija": "Selce",                        "slika": "jpg-small/ck005---20260428_200248.jpg" },
  { "oznaka": "CK6",   "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK7",   "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK8",   "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK9",   "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK10",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK11",  "datum": "05.04.2026", "lokacija": "Jadranovo",                    "slika": "jpg-small/ck011---20260405_113418.jpg" },
  { "oznaka": "CK12",  "datum": "06.04.2026", "lokacija": "Luka Pazdehova",               "slika": "jpg-small/ck012---20260406_144812.jpg" },
  { "oznaka": "CK13",  "datum": "28.04.2026", "lokacija": "Luka Podvorska (Pasja plaža)", "slika": "jpg-small/ck013---20260428_192449.jpg" },
  { "oznaka": "CK14",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK15",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK16",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK17",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK18",  "datum": "28.04.2026", "lokacija": "Glavna luka Crikvenica",       "slika": "jpg-small/ck018---20260428_190504.jpg" },
  { "oznaka": "CK19",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK20",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK21",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK22",  "datum": "28.04.2026", "lokacija": "Črni mul",                    "slika": "jpg-small/ck022---20260428_183158.jpg" },
  { "oznaka": "CK23",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK24",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK25",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK26",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK27",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK28",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK29",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK30",  "datum": "04.04.2026", "lokacija": "Selce",                        "slika": "jpg-small/ck030---20260428_201212.jpg" },
  { "oznaka": "CK31",  "datum": "28.04.2026", "lokacija": "Luka Podvorska (Pasja plaža)", "slika": "jpg-small/ck031---20260428_191635.jpg" },
  { "oznaka": "CK32",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK33",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK34",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK35",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK36",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK37",  "datum": "28.04.2026", "lokacija": "Glavna luka Crikvenica",       "slika": "jpg-small/ck037---20260428_190438.jpg" },
  { "oznaka": "CK38",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK39",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK40",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK41",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK42",  "datum": "28.04.2026", "lokacija": "Glavna luka Crikvenica",       "slika": "jpg-small/ck042---20260428_190634.jpg" },
  { "oznaka": "CK43",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK44",  "datum": "28.04.2026", "lokacija": "Glavna luka Crikvenica",       "slika": "jpg-small/ck044---20260428_190644.jpg" },
  { "oznaka": "CK45",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK46",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK47",  "datum": "28.04.2026", "lokacija": "Selce",                        "slika": "jpg-small/ck047---20260428_200823.jpg" },
  { "oznaka": "CK48",  "datum": "28.04.2026", "lokacija": "Črni mul",                    "slika": "jpg-small/ck048---20260428_183328.jpg" },
  { "oznaka": "CK49",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK50",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK51",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK52",  "datum": "28.04.2026", "lokacija": "Glavna luka Crikvenica",       "slika": "jpg-small/ck052---20260428_190427.jpg" },
  { "oznaka": "CK53",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK54",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK55",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK56",  "datum": "06.04.2026", "lokacija": "Luka Pazdehova",               "slika": "jpg-small/ck056---20260406_144823.jpg" },
  { "oznaka": "CK57",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK58",  "datum": "28.04.2026", "lokacija": "Črni mul",                    "slika": "jpg-small/ck058---20260428_183348.jpg" },
  { "oznaka": "CK59",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK60",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK61",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK62",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK63",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK64",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK65",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK66",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK67",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK68",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK69",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK70",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK71",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK72",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK73",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK74",  "datum": "28.04.2026", "lokacija": "Luka Podvorska (Pasja plaža)", "slika": "jpg-small/ck074---20260428_192711.jpg" },
  { "oznaka": "CK75",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK76",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK77",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK78",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK79",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK80",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK81",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK82",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK83",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK84",  "datum": "27.04.2026", "lokacija": "Luka Brščanovica",             "slika": "jpg-small/ck084---20260427_105607.jpg" },
  { "oznaka": "CK85",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK86",  "datum": "27.04.2026", "lokacija": "Luka Brščanovica",             "slika": "jpg-small/ck086---20260427_105533.jpg" },
  { "oznaka": "CK87",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK88",  "datum": "28.04.2026", "lokacija": "Glavna luka Crikvenica",       "slika": "jpg-small/ck088---20260428_190524.jpg" },
  { "oznaka": "CK89",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK90",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK91",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK92",  "datum": "28.04.2026", "lokacija": "Glavna luka Crikvenica",       "slika": "jpg-small/ck092---20260428_190451.jpg" },
  { "oznaka": "CK93",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK94",  "datum": "05.07.2026", "lokacija": "Jadranovo",                    "slika": "jpg-small/ck094---20260705_192319.jpg" },
  { "oznaka": "CK95",  "datum": "28.04.2026", "lokacija": "Luka Podvorska (Pasja plaža)", "slika": "jpg-small/ck095---20260428_191810.jpg" },
  { "oznaka": "CK96",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK97",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK98",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK99",  "datum": "", "lokacija": "", "slika": "" },
  { "oznaka": "CK100", "datum": "", "lokacija": "", "slika": "" }
];
