var data = {
"povezave":[

    // barve:
    // primary   - temno modra
    // secondary - temno siva     (ne dela)
    // success   - zelena
    // danger    - rdeča
    // warning   - oranžna
    // info      - modra
    // light     - siva           (ne dela)
    // dark      - temna grafitna (ne dela)

    ////////////
    // Krovni //
    ////////////

    {"tip":"Card", "barva":"success", "text":"Projekti", "img":"black-start-48.png"},
      {"tip":"Btn", "barva":"green", "text":"isunz", "link":"https://git.genis.si/genis/isunz", "opis":""},
      {"tip":"Btn", "barva":"dark", "text":"začetni", "link":"https://git.genis.si/", "opis":""},
      {"tip":"Btn", "barva":"dark", "text":"genis", "link":"https://git.genis.si/genis/", "opis":""},

      {"tip":"NL"},
      {"tip":"Btn", "barva":"orange",  "text":"doc&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", 
                                                         "link":"https://git.genis.si/genis/isunz/isunz-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"mr",      "link":"https://git.genis.si/genis/isunz/mrrsp/mrrsp-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"ar",      "link":"https://git.genis.si/genis/isunz/azil/azil-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"db",      "link":"https://git.genis.si/genis/isunz/begunci/begunci-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"pl",      "link":"https://git.genis.si/genis/isunz/potn/potn-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"oi",      "link":"https://git.genis.si/genis/isunz/osiz/osiz-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"rdru",    "link":"https://git.genis.si/genis/isunz/rdru/rdru-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"or",      "link":"https://git.genis.si/genis/isunz/orex/orex-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"erisk",   "link":"https://git.genis.si/genis/isunz/eriskdisp/eriskdisp-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"dw",      "link":"", "opis":"", disabled:"true"},
      {"tip":"Btn", "barva":"orange",  "text":"evp",     "link":"https://git.genis.si/genis/isunz/evp/evp-doc", "opis":""},
      {"tip":"Btn", "barva":"orange",  "text":"gurs",    "link":"", "opis":"", disabled:"true"},
      {"tip":"Btn", "barva":"orange2", "text":"ec",      "link":"https://git.genis.si/genis/e-crp/ecrp-doc", "opis":""},
      {"tip":"Btn", "barva":"orange2", "text":"iomodul", "link":"https://git.genis.si/genis/iomodul/iodis-doc", "opis":""},
      {"tip":"Btn", "barva":"orange2", "text":"isdvk",   "link":"https://git.genis.si/genis/isdvk/isdvk-doc", "opis":""},
      {"tip":"Btn", "barva":"orange2", "text":"ippo", "link":"https://git.genis.si/genis/ippo/ippo-doc", "opis":""},
      {"tip":"NL"},
      {"tip":"Btn", "barva":"blue",  "text":"db&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", 
                                                       "link":"https://git.genis.si/genis/isunz/isunz-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"mr",      "link":"https://git.genis.si/genis/isunz/isunz-db/mrrsp-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"ar",      "link":"https://git.genis.si/genis/isunz/isunz-db/mrrsp-db", "opis":"", disabled:"true"},
      {"tip":"Btn", "barva":"blue",  "text":"db",      "link":"https://git.genis.si/genis/isunz/isunz-db/mrrsp-db", "opis":"", disabled:"true"},
      {"tip":"Btn", "barva":"blue",  "text":"pl",      "link":"https://git.genis.si/genis/isunz/isunz-db/potn-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"oi",      "link":"https://git.genis.si/genis/isunz/isunz-db/osiz-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"rdru",    "link":"https://git.genis.si/genis/isunz/isunz-db/rdru-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"or",      "link":"https://git.genis.si/genis/isunz/isunz-db/orex-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"erisk",   "link":"https://git.genis.si/genis/isunz/isunz-db/erisk-dispatcher-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"dw",      "link":"https://git.genis.si/genis/isunz/isunz-db/mnzdw-db", "opis":""},
      {"tip":"Btn", "barva":"blue",  "text":"evp",     "link":"https://git.genis.si/genis/isunz/isunz-db/mrrsp-db", "opis":"", disabled:"true"},
      {"tip":"Btn", "barva":"blue",  "text":"gurs",    "link":"https://git.genis.si/genis/isunz/isunz-db/gursint-db", "opis":""},
      {"tip":"Btn", "barva":"blue2", "text":"ec",      "link":"https://git.genis.si/genis/e-crp/ecrp-db", "opis":""},
      {"tip":"Btn", "barva":"blue2", "text":"iomodul", "link":"https://git.genis.si/genis/iomodul/iomodul-db", "opis":""},
      {"tip":"Btn", "barva":"blue2", "text":"isdvk",   "link":"https://git.genis.si/genis/isdvk/isdvk-db", "opis":""},
      {"tip":"Btn", "barva":"blue2", "text":"ippo",    "link":"https://git.genis.si/genis/ippo/ippo-db", "opis":""},
      {"tip":"NL"},
      {"tip":"Btn", "barva":"green3", "text":"milestones&nbsp;&nbsp;&nbsp;&nbsp;", "link":"https://git.genis.si/groups/genis/isunz/-/milestones", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"mr", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=mr&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"ar", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=ar&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"db", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=db0&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"pl", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=pl&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"oi", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=oi&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"rdru", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=rdru&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"or", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=or&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"erisk", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=erisk&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"dw", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=dw&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"evp", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=evp&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"gurs", "link":"https://git.genis.si/groups/genis/isunz/-/milestones?search_title=gurs&sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green2", "text":"ec", "link":"https://git.genis.si/groups/genis/e-crp/-/milestones?sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green2", "text":"iomodul", "link":"https://git.genis.si/groups/genis/iomodul/-/milestones?sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green2", "text":"isdvk", "link":"https://git.genis.si/groups/genis/isdvk/-/milestones?sort=start_date_desc&state=all", "opis":""},
      {"tip":"Btn", "barva":"green2", "text":"ippo", "link":"https://git.genis.si/groups/genis/ippo/-/milestones?sort=start_date_desc&state=all", "opis":""},
      {"tip":"NL"},
      {"tip":"Btn", "barva":"brown", "text":"release mon.", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"mr", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=MR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"ar", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=AR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"db", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=DB", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"pl", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=PL", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"oi", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=OI", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"rdru", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=RDRU", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"or", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=OR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"erisk", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=ERISK", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"dw", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=MNZDW", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"evp", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=EVP", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"gurs", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISUNZ&irs=GURS-INT", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"ec", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=eCRP 2022-24 razvoj&irs=ECRP", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"iomodul", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=IOMVZDR-2023&irs=IOMODUL", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"isdvk", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=ISDVK&irs=ISDVK", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"ippo", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/?project=NIJZ-IPPO-24-26&irs=IPPO", "opis":""},
      {"tip":"NL"},
      {"tip":"Btn", "barva":"brown", "text":"pregled nam.", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"mr", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=MR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"ar", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=AR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"db", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=DB", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"pl", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=PL", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"oi", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=OI", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"rdru", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=RDRU", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"or", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=OR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"erisk", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=ERISK", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"dw", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=MNZDW", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"evp", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=EVP", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"gurs", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISUNZ&irs=GURS-INT", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"ec", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=eCRP 2022-24 razvoj&irs=ECRP", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"iomodul", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=IOMVZDR-2023&irs=IOMODUL", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"isdvk", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=ISDVK&irs=ISDVK", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"ippo", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Pregled%20Namestitev/?projects=NIJZ-IPPO-24-26&irs=IPPO", "opis":""},
      {"tip":"NL"},
      {"tip":"Btn", "barva":"brown", "text":"vsebina ver.&nbsp;&nbsp;", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"mr", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=MR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"ar", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=AR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"db", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=DB", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"pl", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=PL", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"oi", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=OI", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"rdru", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=RDRU", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"or", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=OR", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"erisk", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=ERISK", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"dw", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=MNZDW", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"evp", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=EVP", "opis":""},
      {"tip":"Btn", "barva":"brown", "text":"gurs", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISUNZ&ir=GURS-INT", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"ec", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=eCRP 2022-24 razvoj&ir=ECRP", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"iomodul", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=IOMVZDR-2023&ir=IOMODUL", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"isdvk", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=ISDVK&ir=ISDVK", "opis":""},
      {"tip":"Btn", "barva":"brown2", "text":"ippo", "link":"https://genis.pages.genis.si/gendevnext/RELEASE-MONITOR/RELEASE%20MONITOR/Vsebina%20verzije/?project=NIJZ-IPPO-24-26&ir=IPPO", "opis":""},
      {"tip":"NL"},
      {"tip":"Btn", "barva":"redmine", "text":"redmine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", "link":"https://dro.sigov.si/redmine/projects/is-dunz/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"mr", "link":"https://dro.sigov.si/redmine/projects/crp/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"ar", "link":"https://dro.sigov.si/redmine/projects/azil/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"db", "link":"https://dro.sigov.si/redmine/projects/begunci/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"pl", "link":"https://dro.sigov.si/redmine/projects/potn/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"oi", "link":"https://dro.sigov.si/redmine/projects/oziz/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"rdru", "link":"https://dro.sigov.si/redmine/projects/rdru/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"or", "link":"https://dro.sigov.si/redmine/projects/orex/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"erisk", "link":"https://dro.sigov.si/redmine/projects/erisk/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"dw", "link":"https://dro.sigov.si/redmine/projects/mnzwh/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"evp", "link":"https://dro.sigov.si/redmine/projects/evp/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine", "text":"gurs", "link":"https://dro.sigov.si/redmine/projects/gurs-int/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine2", "text":"ec", "link":"https://dro.sigov.si/redmine/projects/ecrp/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine2", "text":"iomodul", "link":"https://dro.sigov.si/redmine/projects/io-modul/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine2", "text":"isdvk", "link":"https://dro.sigov.si/redmine/projects/is-dvk/issues", "opis":""},
      {"tip":"Btn", "barva":"redmine2", "text":"ippo", "link":"", "opis":"", disabled:"true"},
      {"tip":"CardEnd"},
//    {"tip":"Card", "barva":"red", "text":"Doc", "img":"black-doc-48.png"},
//      {"tip":"Btn", "barva":"red", "text":"isunz-doc", "link":"https://git.genis.si/genis/isunz/isunz-doc", "opis":""},
//      {"tip":"NL"},
//      {"tip":"Btn", "barva":"red", "text":"mrrsp-doc", "link":"https://git.genis.si/genis/isunz/mrrsp/mrrsp-doc", "opis":""},
//      {"tip":"Btn", "barva":"red", "text":"potn-doc", "link":"https://git.genis.si/genis/isunz/potn/potn-doc", "opis":""},
//      {"tip":"Btn", "barva":"red", "text":"osiz-doc", "link":"https://git.genis.si/genis/isunz/osiz/osiz-doc", "opis":""},
//      {"tip":"Btn", "barva":"red", "text":"rdru-doc", "link":"https://git.genis.si/genis/isunz/rdru/rdru-doc", "opis":""},
//      {"tip":"Btn", "barva":"red", "text":"evp-doc", "link":"https://git.genis.si/genis/isunz/evp/evp-doc", "opis":""},
//      {"tip":"NL"},
//      {"tip":"Btn", "barva":"red", "text":"ecrp-doc", "link":"https://git.genis.si/genis/e-crp/ecrp-doc", "opis":""},
//      {"tip":"Btn", "barva":"red", "text":"isdvk-doc", "link":"https://git.genis.si/genis/isdvk/isdvk-doc", "opis":""},
//      {"tip":"Btn", "barva":"red", "text":"iodis-doc", "link":"https://git.genis.si/genis/iomodul/iodis-doc", "opis":""},
//      {"tip":"CardEnd"},
//    {"tip":"Card", "barva":"info", "text":"DB", "img":"black-db-48.png"},
//      {"tip":"Btn", "barva":"blue", "text":"isunz-db", "link":"https://git.genis.si/genis/isunz/isunz-db", "opis":""},
//      {"tip":"NL"},
//      {"tip":"Btn", "barva":"blue2", "text":"mrrsp-db", "link":"https://git.genis.si/genis/isunz/isunz-db/mrrsp-db", "opis":""},
//      {"tip":"Btn", "barva":"blue2", "text":"potn-db", "link":"https://git.genis.si/genis/isunz/isunz-db/potn-db", "opis":""},
//      {"tip":"Btn", "barva":"blue2", "text":"osiz-db", "link":"https://git.genis.si/genis/isunz/isunz-db/osiz-db", "opis":""},
//      {"tip":"Btn", "barva":"blue2", "text":"rdru-db", "link":"https://git.genis.si/genis/isunz/isunz-db/rdru-db", "opis":""},
//      {"tip":"Btn", "barva":"blue2", "text":"orex-db", "link":"https://git.genis.si/genis/isunz/isunz-db/orex-db", "opis":""},
//      {"tip":"NL"},
//      {"tip":"Btn", "barva":"blue2", "text":"erisk-disp.-db", "link":"https://git.genis.si/genis/isunz/isunz-db/erisk-dispatcher-db", "opis":""},
//      {"tip":"Btn", "barva":"blue2", "text":"mnzdw-db", "link":"https://git.genis.si/genis/isunz/isunz-db/mnzdw-db", "opis":""},
//      {"tip":"Btn", "barva":"blue2", "text":"gursint-db", "link":"https://git.genis.si/genis/isunz/isunz-db/gursint-db", "opis":""},
//      {"tip":"NL"},
//      {"tip":"Btn", "barva":"blue", "text":"ecrp-db", "link":"https://git.genis.si/genis/e-crp/ecrp-db", "opis":""},
//      {"tip":"Btn", "barva":"blue", "text":"isdvk-db", "link":"https://git.genis.si/genis/isdvk/isdvk-db", "opis":""},
//      {"tip":"Btn", "barva":"blue", "text":"iomodul-db", "link":"https://git.genis.si/genis/iomodul/iomodul-db", "opis":""},
//      {"tip":"CardEnd"},
    {"tip":"Card", "barva":"success", "text":"Navodila", "img":"black-hlp-48.png"},
      {"tip":"Btn", "barva":"green3", "text":"Uporaba Git", "link":"https://genis.pages.genis.si/gendevnext/Razvoj/Izdaja%20verzije/Oracle%20GitLab/", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"Potek razvoja", "link":"https://genis.pages.genis.si/gendevnext/Proces%20razvoja/Proces%20z%20uporabo%20GitLab/Proces%20razvoja/", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"Proces razvoja", "link":"https://genis.pages.genis.si/gendevnext/Razvoj/Navodila%20in%20baza%20znanja/Uporaba%20GIT/", "opis":""},
      {"tip":"Btn", "barva":"green3", "text":"Hitra checklista", "link":"https://genis.pages.genis.si/gendevnext/Proces%20razvoja/Proces%20z%20uporabo%20GitLab/Proces%20razvoja/#hitra-checklista", "opis":""},
      {"tip":"Btn", "barva":"dark", "text":"Url4D", "link":"https://genis.pages.genis.si/gendevnext/Projekti/URL4Dnext", "opis":""},
      {"tip":"Btn", "barva":"dark", "text":"NASA", "link":"https://nasa.apps.genis.si/nasa/", "opis":""},
      {"tip":"CardEnd"}
]  
};

